"""
05_statevector.py

Goal
----
Learn how to inspect quantum states directly with Qiskit's Statevector class.

This example introduces:

    - Statevector
    - Statevector.from_instruction()
    - amplitudes
    - probabilities
    - basis-state ordering
    - global phase
    - relative phase
    - multi-qubit states
    - normalization

Theory
------
For one qubit:

    |psi> = alpha|0> + beta|1>

Qiskit represents this state as:

    [alpha, beta]

For two qubits:

    |psi> =
        a|00> +
        b|01> +
        c|10> +
        d|11>

the statevector contains four complex amplitudes.

For n qubits, the statevector has:

    2^n

complex amplitudes.
"""

from math import sqrt

import numpy as np

from qiskit import QuantumCircuit
from qiskit.quantum_info import Statevector


def show_state(
    name: str,
    state: Statevector,
) -> None:
    """Display amplitudes and computational-basis probabilities."""

    print("=" * 70)
    print(name)
    print("=" * 70)

    print("\nStatevector:")
    print(state)

    print("\nRaw amplitudes:")
    print(state.data)

    print("\nProbabilities:")
    print(
        state.probabilities_dict()
    )

    print()


def example_default_zero_state() -> None:
    """
    Create |0> directly.

    Statevector accepts an array of complex amplitudes:

        |0> = [1, 0]
    """

    state = Statevector(
        [
            1,
            0,
        ]
    )

    show_state(
        "The state |0>",
        state,
    )


def example_one_state() -> None:
    """
    Create |1> directly.

        |1> = [0, 1]
    """

    state = Statevector(
        [
            0,
            1,
        ]
    )

    show_state(
        "The state |1>",
        state,
    )


def example_plus_state_directly() -> None:
    """
    Construct |+> manually.

        |+> =
        (|0> + |1>) / sqrt(2)

    Therefore:

        alpha = 1/sqrt(2)
        beta  = 1/sqrt(2)
    """

    state = Statevector(
        [
            1 / sqrt(2),
            1 / sqrt(2),
        ]
    )

    show_state(
        "The state |+> constructed manually",
        state,
    )


def example_plus_state_from_circuit() -> None:
    """
    Construct the same |+> state using a circuit.

    Start:

        |0>

    Apply H:

        H|0> = |+>

    Statevector.from_instruction() evaluates the circuit exactly.
    """

    circuit = QuantumCircuit(1)

    circuit.h(0)

    state = Statevector.from_instruction(
        circuit
    )

    print("=" * 70)
    print("|+> generated by a circuit")
    print("=" * 70)

    print("\nCircuit:")
    print(circuit.draw(output="text"))

    print("\nStatevector:")
    print(state)

    print("\nProbabilities:")
    print(
        state.probabilities_dict()
    )

    print()


def example_amplitude_vs_probability() -> None:
    """
    Demonstrate the difference between amplitude and probability.

    Consider:

        |psi> =
        sqrt(3)/2 |0>
        +
        1/2 |1>

    The amplitudes are:

        alpha = sqrt(3)/2
        beta  = 1/2

    But the probabilities are:

        P(0) = |alpha|^2 = 3/4

        P(1) = |beta|^2 = 1/4

    Amplitude is NOT probability.
    """

    state = Statevector(
        [
            sqrt(3) / 2,
            1 / 2,
        ]
    )

    show_state(
        "Amplitude versus probability",
        state,
    )


def example_complex_amplitudes() -> None:
    """
    Quantum amplitudes may be complex.

    Consider:

        |psi> =
        1/sqrt(2)|0>
        +
        i/sqrt(2)|1>

    Both outcomes still have probability 1/2 because:

        |i/sqrt(2)|^2 = 1/2
    """

    state = Statevector(
        [
            1 / sqrt(2),
            1j / sqrt(2),
        ]
    )

    show_state(
        "State with complex amplitudes",
        state,
    )


def example_relative_phase() -> None:
    """
    Compare |+> and |->.

        |+> =
        (|0> + |1>) / sqrt(2)

        |-> =
        (|0> - |1>) / sqrt(2)

    Their computational-basis probabilities are identical:

        P(0) = P(1) = 1/2

    but they are different quantum states because the relative
    phase is different.
    """

    plus = Statevector(
        [
            1 / sqrt(2),
            1 / sqrt(2),
        ]
    )

    minus = Statevector(
        [
            1 / sqrt(2),
            -1 / sqrt(2),
        ]
    )

    show_state(
        "|+>",
        plus,
    )

    show_state(
        "|->",
        minus,
    )


def example_global_phase() -> None:
    """
    Demonstrate global phase.

    States:

        |psi>

    and:

        exp(i phi)|psi>

    represent the same physical pure state.

    Example:

        |0>

    and:

        i|0>

    have identical measurement probabilities.
    """

    state_a = Statevector(
        [
            1,
            0,
        ]
    )

    state_b = Statevector(
        [
            1j,
            0,
        ]
    )

    print("=" * 70)
    print("Global phase")
    print("=" * 70)

    print("\nState A:")
    print(state_a)

    print("\nState B:")
    print(state_b)

    print("\nProbabilities A:")
    print(
        state_a.probabilities_dict()
    )

    print("\nProbabilities B:")
    print(
        state_b.probabilities_dict()
    )

    print(
        "\nThe vectors differ, but measurement statistics are identical."
    )

    print()


def example_two_qubit_basis_state() -> None:
    """
    Introduce a two-qubit statevector.

    A two-qubit system has four computational basis states:

        |00>
        |01>
        |10>
        |11>

    and therefore four amplitudes.

    Qiskit's basis ordering should always be checked carefully
    when mapping qubit indices to printed bit strings.
    """

    circuit = QuantumCircuit(2)

    # Flip q0.
    circuit.x(0)

    state = Statevector.from_instruction(
        circuit
    )

    print("=" * 70)
    print("Two-qubit basis state")
    print("=" * 70)

    print("\nCircuit:")
    print(circuit.draw(output="text"))

    print("\nStatevector:")
    print(state)

    print("\nProbabilities:")
    print(
        state.probabilities_dict()
    )

    print()


def example_bell_state() -> None:
    """
    Inspect the Bell state before measurement.

    Circuit:

        H(q0)
        CX(q0, q1)

    produces:

        (|00> + |11>) / sqrt(2)

    The statevector should therefore contain non-zero amplitudes
    only for |00> and |11>.
    """

    circuit = QuantumCircuit(2)

    circuit.h(0)
    circuit.cx(0, 1)

    state = Statevector.from_instruction(
        circuit
    )

    print("=" * 70)
    print("Bell state")
    print("=" * 70)

    print("\nCircuit:")
    print(circuit.draw(output="text"))

    print("\nStatevector:")
    print(state)

    print("\nProbabilities:")
    print(
        state.probabilities_dict()
    )

    print()


def example_normalization() -> None:
    """
    Verify the normalization condition.

    A valid pure quantum state satisfies:

        sum_i |alpha_i|^2 = 1

    For:

        (|00> + |11>) / sqrt(2)

    we have:

        1/2 + 1/2 = 1
    """

    circuit = QuantumCircuit(2)

    circuit.h(0)
    circuit.cx(0, 1)

    state = Statevector.from_instruction(
        circuit
    )

    amplitudes = state.data

    norm_squared = np.sum(
        np.abs(amplitudes) ** 2
    )

    print("=" * 70)
    print("Normalization")
    print("=" * 70)

    print("\nStatevector:")
    print(state)

    print("\nSum of squared amplitudes:")
    print(norm_squared)

    print()


def example_number_of_amplitudes() -> None:
    """
    Show the exponential size of a statevector.

    For n qubits:

        number of amplitudes = 2^n

    This is one reason classical statevector simulation becomes
    expensive as the number of qubits grows.
    """

    print("=" * 70)
    print("Statevector size")
    print("=" * 70)

    for qubits in range(1, 11):
        amplitudes = 2 ** qubits

        print(
            f"{qubits:2d} qubits -> "
            f"{amplitudes:5d} amplitudes"
        )

    print()


def main() -> None:
    """Run all Statevector examples."""

    example_default_zero_state()
    example_one_state()

    example_plus_state_directly()
    example_plus_state_from_circuit()

    example_amplitude_vs_probability()
    example_complex_amplitudes()

    example_relative_phase()
    example_global_phase()

    example_two_qubit_basis_state()
    example_bell_state()

    example_normalization()

    example_number_of_amplitudes()


if __name__ == "__main__":
    main()
